version: '3'

services:
  zk1:
    image: bitnami/zookeeper:3.6.2
    container_name: zk1
    hostname: zk1
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zk2:2888:3888,zk3:2888:3888

  zk2:
    image: bitnami/zookeeper:3.6.2
    container_name: zk2
    hostname: zk2
    ports:
      - "2182:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zk1:2888:3888,0.0.0.0:2888:3888,zk3:2888:3888

  zk3:
    image: bitnami/zookeeper:3.6.2
    container_name: zk3
    hostname: zk3
    ports:
      - "2183:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zk1:2888:3888,zk2:2888:3888,0.0.0.0:2888:3888