version: '3.8'

services:
  zookeeper1:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zk-data1:/bitnami/zookeeper

  zookeeper2:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper2
    ports:
      - "2182:2181"
    environment:
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper1:2888:3888,0.0.0.0:2888:3888,zookeeper3:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zk-data2:/bitnami/zookeeper

  zookeeper3:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper3
    ports:
      - "2183:2181"
    environment:
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,0.0.0.0:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zk-data3:/bitnami/zookeeper
